#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtencionTemprana
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PNL_NSJP2")]
	public partial class dcOrientacionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dcOrientacionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PGJ_NSJPConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcOrientacionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcOrientacionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcOrientacionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcOrientacionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarTurno", IsComposable=true)]
		public object agregarTurno([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cNumeroTurno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string cTipoTurno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Paterno", DbType="VarChar(50)")] string paterno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Materno", DbType="VarChar(50)")] string materno)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cNumeroTurno, cTipoTurno, nombre, paterno, materno).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaClasificacionCorporacion")]
		public ISingleResult<consultaClasificacionCorporacionResult> consultaClasificacionCorporacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CLASIFICACION", DbType="SmallInt")] System.Nullable<short> iD_CLASIFICACION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CLASIFICACION);
			return ((ISingleResult<consultaClasificacionCorporacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaDesHechos")]
		public ISingleResult<consultaDesHechosResult> consultaDesHechos([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpeta", DbType="Int")] System.Nullable<int> idCarpeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpeta);
			return ((ISingleResult<consultaDesHechosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaEstadoMunicipio")]
		public ISingleResult<consultaEstadoMunicipioResult> consultaEstadoMunicipio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PAIS", DbType="SmallInt")] System.Nullable<short> iD_PAIS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ESTDO", DbType="SmallInt")] System.Nullable<short> iD_ESTDO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PAIS, iD_ESTDO);
			return ((ISingleResult<consultaEstadoMunicipioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaLocalidadCalle")]
		public ISingleResult<consultaLocalidadCalleResult> consultaLocalidadCalle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PAIS", DbType="SmallInt")] System.Nullable<short> iD_PAIS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ESTDO", DbType="SmallInt")] System.Nullable<short> iD_ESTDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MNCPIO", DbType="SmallInt")] System.Nullable<short> iD_MNCPIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_LOCALIDAD", DbType="SmallInt")] System.Nullable<short> iD_LOCALIDAD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PAIS, iD_ESTDO, iD_MNCPIO, iD_LOCALIDAD);
			return ((ISingleResult<consultaLocalidadCalleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaLocalidadColonia")]
		public ISingleResult<consultaLocalidadColoniaResult> consultaLocalidadColonia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PAIS", DbType="SmallInt")] System.Nullable<short> iD_PAIS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ESTDO", DbType="SmallInt")] System.Nullable<short> iD_ESTDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MNCPIO", DbType="SmallInt")] System.Nullable<short> iD_MNCPIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_LOCALIDAD", DbType="SmallInt")] System.Nullable<short> iD_LOCALIDAD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PAIS, iD_ESTDO, iD_MNCPIO, iD_LOCALIDAD);
			return ((ISingleResult<consultaLocalidadColoniaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaMunicipioLocalidad")]
		public ISingleResult<consultaMunicipioLocalidadResult> consultaMunicipioLocalidad([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PAIS", DbType="SmallInt")] System.Nullable<short> iD_PAIS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ESTDO", DbType="SmallInt")] System.Nullable<short> iD_ESTDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MNCPIO", DbType="SmallInt")] System.Nullable<short> iD_MNCPIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PAIS, iD_ESTDO, iD_MNCPIO);
			return ((ISingleResult<consultaMunicipioLocalidadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaPaisEstado")]
		public ISingleResult<consultaPaisEstadoResult> consultaPaisEstado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PAIS", DbType="SmallInt")] System.Nullable<short> iD_PAIS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PAIS);
			return ((ISingleResult<consultaPaisEstadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fechaServidor")]
		public ISingleResult<fechaServidorResult> fechaServidor()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<fechaServidorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.llamarTurno")]
		public ISingleResult<llamarTurnoResult> llamarTurno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUnidad", DbType="SmallInt")] System.Nullable<short> idUnidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUnidad);
			return ((ISingleResult<llamarTurnoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TurnoMaxAtencion")]
		public ISingleResult<TurnoMaxAtencionResult> TurnoMaxAtencion()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TurnoMaxAtencionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TurnoMaxMediacion")]
		public ISingleResult<TurnoMaxMediacionResult> TurnoMaxMediacion()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TurnoMaxMediacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TurnoMaxOficialia")]
		public ISingleResult<TurnoMaxOficialiaResult> TurnoMaxOficialia()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TurnoMaxOficialiaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TurnoMaxOrientacion")]
		public ISingleResult<TurnoMaxOrientacionResult> TurnoMaxOrientacion()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TurnoMaxOrientacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ValidaTurnoOrientacio", IsComposable=true)]
		public object ValidaTurnoOrientacio()
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VALIDAR_PGJ_CARPETA_RAC")]
		public int VALIDAR_PGJ_CARPETA_RAC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numero", DbType="VarChar(5)")] string numero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Año", DbType="VarChar(4)")] string año, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> x)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numero, año, x);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VALIDAR_PGJ_DELITOS")]
		public int VALIDAR_PGJ_DELITOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCARPETA", DbType="Int")] System.Nullable<int> iDCARPETA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRINCIPAL", DbType="SmallInt")] System.Nullable<short> iD_PRINCIPAL, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> x)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCARPETA, iD_PRINCIPAL, x);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaIdPersonaMax")]
		public ISingleResult<consultaIdPersonaMaxResult> consultaIdPersonaMax([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Paterno", DbType="VarChar(50)")] string paterno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Materno", DbType="VarChar(50)")] string materno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paterno, materno, nombre);
			return ((ISingleResult<consultaIdPersonaMaxResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaMarcaSubMarca")]
		public ISingleResult<consultaMarcaSubMarcaResult> consultaMarcaSubMarca([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Idmarca", DbType="SmallInt")] System.Nullable<short> idmarca)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idmarca);
			return ((ISingleResult<consultaMarcaSubMarcaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VALIDAR_PGJ_CARPETA_NUC")]
		public int VALIDAR_PGJ_CARPETA_NUC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(2)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Municipio", DbType="VarChar(2)")] string municipio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Unidad", DbType="VarChar(3)")] string unidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numero", DbType="VarChar(5)")] string numero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Año", DbType="VarChar(4)")] string año, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> x)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), estado, municipio, unidad, numero, año, x);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SolicitarNuc")]
		public ISingleResult<SolicitarNucResult> SolicitarNuc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpeta", DbType="Int")] System.Nullable<int> idCarpeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpeta);
			return ((ISingleResult<SolicitarNucResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ConsultaImputadoDefensor")]
		public ISingleResult<ConsultaImputadoDefensorResult> ConsultaImputadoDefensor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpeta", DbType="Int")] System.Nullable<int> idCarpeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpeta);
			return ((ISingleResult<ConsultaImputadoDefensorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaAccionDelito")]
		public ISingleResult<consultaAccionDelitoResult> consultaAccionDelito([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDelito", DbType="SmallInt")] System.Nullable<short> idDelito)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDelito);
			return ((ISingleResult<consultaAccionDelitoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaPusoDisposicion")]
		public ISingleResult<consultaPusoDisposicionResult> consultaPusoDisposicion()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<consultaPusoDisposicionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MarcadorDenunciante")]
		public ISingleResult<MarcadorDenuncianteResult> MarcadorDenunciante([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpeta", DbType="Int")] System.Nullable<int> idCarpeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpeta);
			return ((ISingleResult<MarcadorDenuncianteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MarcadorOfendido")]
		public ISingleResult<MarcadorOfendidoResult> MarcadorOfendido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpeta", DbType="Int")] System.Nullable<int> idCarpeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpeta);
			return ((ISingleResult<MarcadorOfendidoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MarcadorImputado")]
		public ISingleResult<MarcadorImputadoResult> MarcadorImputado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpeta", DbType="Int")] System.Nullable<int> idCarpeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpeta);
			return ((ISingleResult<MarcadorImputadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertaDefensor")]
		public int InsertaDefensor(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpeta", DbType="Int")] System.Nullable<int> idCarpeta, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPersona", DbType="Int")] System.Nullable<int> idPersona, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Paterno", DbType="VarChar(50)")] string paterno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Materno", DbType="VarChar(50)")] string materno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEFENSOR_PUB_PRIV", DbType="SmallInt")] System.Nullable<short> dEFENSOR_PUB_PRIV, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoActor", DbType="SmallInt")] System.Nullable<short> idTipoActor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_IDENTIFICACION", DbType="SmallInt")] System.Nullable<short> iD_IDENTIFICACION, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FOLIO", DbType="VarChar(50)")] string fOLIO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="VarChar(50)")] string tELEFONO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_NACIONALIDAD", DbType="SmallInt")] System.Nullable<short> iD_NACIONALIDAD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PAIS_ORIGEN", DbType="SmallInt")] System.Nullable<short> iD_PAIS_ORIGEN, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ESTADO_ORIGEN", DbType="SmallInt")] System.Nullable<short> iD_ESTADO_ORIGEN, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MUNICIPIO_ORIGEN", DbType="SmallInt")] System.Nullable<short> iD_MUNICIPIO_ORIGEN, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PAIS", DbType="SmallInt")] System.Nullable<short> iD_PAIS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ESTADO", DbType="SmallInt")] System.Nullable<short> iD_ESTADO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MUNICIPIO", DbType="SmallInt")] System.Nullable<short> iD_MUNICIPIO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_LOCALIDAD", DbType="SmallInt")] System.Nullable<short> iD_LOCALIDAD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_COLONIA", DbType="SmallInt")] System.Nullable<short> iD_COLONIA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CALLE", DbType="SmallInt")] System.Nullable<short> iD_CALLE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ENTRE_CALLE", DbType="SmallInt")] System.Nullable<short> iD_ENTRE_CALLE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Y_CALLE", DbType="SmallInt")] System.Nullable<short> iD_Y_CALLE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO", DbType="VarChar(50)")] string nUMERO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MANZANA", DbType="VarChar(50)")] string mANZANA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LOTE", DbType="VarChar(50)")] string lOTE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MUNICIPIO_DEFENSOR", DbType="SmallInt")] System.Nullable<short> iD_MUNICIPIO_DEFENSOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpeta, idPersona, paterno, materno, nombre, dEFENSOR_PUB_PRIV, idTipoActor, iD_IDENTIFICACION, fOLIO, tELEFONO, iD_NACIONALIDAD, iD_PAIS_ORIGEN, iD_ESTADO_ORIGEN, iD_MUNICIPIO_ORIGEN, iD_PAIS, iD_ESTADO, iD_MUNICIPIO, iD_LOCALIDAD, iD_COLONIA, iD_CALLE, iD_ENTRE_CALLE, iD_Y_CALLE, nUMERO, mANZANA, lOTE, iD_MUNICIPIO_DEFENSOR);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MarcadorTestigo")]
		public ISingleResult<MarcadorTestigoResult> MarcadorTestigo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpeta", DbType="Int")] System.Nullable<int> idCarpeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpeta);
			return ((ISingleResult<MarcadorTestigoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MarcadorDefensor")]
		public ISingleResult<MarcadorDefensorResult> MarcadorDefensor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpeta", DbType="Int")] System.Nullable<int> idCarpeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpeta);
			return ((ISingleResult<MarcadorDefensorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VALIDAR_PGJ_CARPETA_NUM")]
		public int VALIDAR_PGJ_CARPETA_NUM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(2)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Municipio", DbType="VarChar(2)")] string municipio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Unidad", DbType="VarChar(3)")] string unidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numero", DbType="VarChar(5)")] string numero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Año", DbType="VarChar(4)")] string año, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> x)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), estado, municipio, unidad, numero, año, x);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VALIDAR_PGJ_CARPETA_NAC")]
		public int VALIDAR_PGJ_CARPETA_NAC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numero", DbType="VarChar(5)")] string numero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Año", DbType="VarChar(4)")] string año, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> x)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numero, año, x);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VALIDAR_NUM_INICIADA")]
		public int VALIDAR_NUM_INICIADA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCARPETA", DbType="Int")] System.Nullable<int> iDCARPETA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MUNICIPIO_INICIADA", DbType="SmallInt")] System.Nullable<short> iD_MUNICIPIO_INICIADA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> x)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCARPETA, iD_MUNICIPIO_INICIADA, x);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VALIDAR_NUM_CUM_DIFERIDO")]
		public int VALIDAR_NUM_CUM_DIFERIDO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCARPETA", DbType="Int")] System.Nullable<int> iDCARPETA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MUNICIPIO", DbType="SmallInt")] System.Nullable<short> iD_MUNICIPIO, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> x)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCARPETA, iD_MUNICIPIO, x);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InvitadoNombreNUM")]
		public ISingleResult<InvitadoNombreNUMResult> InvitadoNombreNUM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpeta", DbType="Int")] System.Nullable<int> idCarpeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpeta);
			return ((ISingleResult<InvitadoNombreNUMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SolicitanteNombreNUM")]
		public ISingleResult<SolicitanteNombreNUMResult> SolicitanteNombreNUM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpeta", DbType="Int")] System.Nullable<int> idCarpeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpeta);
			return ((ISingleResult<SolicitanteNombreNUMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaIdAcuerdoDiferidoMax")]
		public ISingleResult<consultaIdAcuerdoDiferidoMaxResult> consultaIdAcuerdoDiferidoMax()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<consultaIdAcuerdoDiferidoMaxResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ComboFoto")]
		public ISingleResult<SP_ComboFotoResult> SP_ComboFoto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPersona", DbType="Int")] System.Nullable<int> idPersona)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPersona);
			return ((ISingleResult<SP_ComboFotoResult>)(result.ReturnValue));
		}
	}
	
	public partial class consultaClasificacionCorporacionResult
	{
		
		private System.Nullable<short> _ID_CORPORACION;
		
		private System.Nullable<short> _ID_CLASIFICACION;
		
		private string _CORPORACION;
		
		public consultaClasificacionCorporacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CORPORACION", DbType="SmallInt")]
		public System.Nullable<short> ID_CORPORACION
		{
			get
			{
				return this._ID_CORPORACION;
			}
			set
			{
				if ((this._ID_CORPORACION != value))
				{
					this._ID_CORPORACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLASIFICACION", DbType="SmallInt")]
		public System.Nullable<short> ID_CLASIFICACION
		{
			get
			{
				return this._ID_CLASIFICACION;
			}
			set
			{
				if ((this._ID_CLASIFICACION != value))
				{
					this._ID_CLASIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORPORACION", DbType="VarChar(50)")]
		public string CORPORACION
		{
			get
			{
				return this._CORPORACION;
			}
			set
			{
				if ((this._CORPORACION != value))
				{
					this._CORPORACION = value;
				}
			}
		}
	}
	
	public partial class consultaDesHechosResult
	{
		
		private System.Nullable<int> _ID_CARPETA;
		
		private System.Nullable<int> _ID_HECHOS;
		
		private string _DESCRIPCION;
		
		private System.Nullable<System.DateTime> _FECHA_REGISTRO;
		
		public consultaDesHechosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CARPETA", DbType="Int")]
		public System.Nullable<int> ID_CARPETA
		{
			get
			{
				return this._ID_CARPETA;
			}
			set
			{
				if ((this._ID_CARPETA != value))
				{
					this._ID_CARPETA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HECHOS", DbType="Int")]
		public System.Nullable<int> ID_HECHOS
		{
			get
			{
				return this._ID_HECHOS;
			}
			set
			{
				if ((this._ID_HECHOS != value))
				{
					this._ID_HECHOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(MAX)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class consultaEstadoMunicipioResult
	{
		
		private short _ID_MNCPIO;
		
		private short _ID_ESTDO;
		
		private short _ID_PAIS;
		
		private string _MNCPIO;
		
		public consultaEstadoMunicipioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MNCPIO", DbType="SmallInt NOT NULL")]
		public short ID_MNCPIO
		{
			get
			{
				return this._ID_MNCPIO;
			}
			set
			{
				if ((this._ID_MNCPIO != value))
				{
					this._ID_MNCPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTDO", DbType="SmallInt NOT NULL")]
		public short ID_ESTDO
		{
			get
			{
				return this._ID_ESTDO;
			}
			set
			{
				if ((this._ID_ESTDO != value))
				{
					this._ID_ESTDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PAIS", DbType="SmallInt NOT NULL")]
		public short ID_PAIS
		{
			get
			{
				return this._ID_PAIS;
			}
			set
			{
				if ((this._ID_PAIS != value))
				{
					this._ID_PAIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNCPIO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MNCPIO
		{
			get
			{
				return this._MNCPIO;
			}
			set
			{
				if ((this._MNCPIO != value))
				{
					this._MNCPIO = value;
				}
			}
		}
	}
	
	public partial class consultaLocalidadCalleResult
	{
		
		private short _ID_CLLE;
		
		private short _ID_LCLDD;
		
		private short _ID_MNCPIO;
		
		private short _ID_ESTDO;
		
		private short _ID_PAIS;
		
		private string _CLLE;
		
		public consultaLocalidadCalleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLLE", DbType="SmallInt NOT NULL")]
		public short ID_CLLE
		{
			get
			{
				return this._ID_CLLE;
			}
			set
			{
				if ((this._ID_CLLE != value))
				{
					this._ID_CLLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LCLDD", DbType="SmallInt NOT NULL")]
		public short ID_LCLDD
		{
			get
			{
				return this._ID_LCLDD;
			}
			set
			{
				if ((this._ID_LCLDD != value))
				{
					this._ID_LCLDD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MNCPIO", DbType="SmallInt NOT NULL")]
		public short ID_MNCPIO
		{
			get
			{
				return this._ID_MNCPIO;
			}
			set
			{
				if ((this._ID_MNCPIO != value))
				{
					this._ID_MNCPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTDO", DbType="SmallInt NOT NULL")]
		public short ID_ESTDO
		{
			get
			{
				return this._ID_ESTDO;
			}
			set
			{
				if ((this._ID_ESTDO != value))
				{
					this._ID_ESTDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PAIS", DbType="SmallInt NOT NULL")]
		public short ID_PAIS
		{
			get
			{
				return this._ID_PAIS;
			}
			set
			{
				if ((this._ID_PAIS != value))
				{
					this._ID_PAIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLLE", DbType="VarChar(100)")]
		public string CLLE
		{
			get
			{
				return this._CLLE;
			}
			set
			{
				if ((this._CLLE != value))
				{
					this._CLLE = value;
				}
			}
		}
	}
	
	public partial class consultaLocalidadColoniaResult
	{
		
		private short _ID_CLNIA;
		
		private short _ID_LCLDD;
		
		private short _ID_MNCPIO;
		
		private short _ID_ESTDO;
		
		private short _ID_PAIS;
		
		private string _CLNIA;
		
		public consultaLocalidadColoniaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLNIA", DbType="SmallInt NOT NULL")]
		public short ID_CLNIA
		{
			get
			{
				return this._ID_CLNIA;
			}
			set
			{
				if ((this._ID_CLNIA != value))
				{
					this._ID_CLNIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LCLDD", DbType="SmallInt NOT NULL")]
		public short ID_LCLDD
		{
			get
			{
				return this._ID_LCLDD;
			}
			set
			{
				if ((this._ID_LCLDD != value))
				{
					this._ID_LCLDD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MNCPIO", DbType="SmallInt NOT NULL")]
		public short ID_MNCPIO
		{
			get
			{
				return this._ID_MNCPIO;
			}
			set
			{
				if ((this._ID_MNCPIO != value))
				{
					this._ID_MNCPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTDO", DbType="SmallInt NOT NULL")]
		public short ID_ESTDO
		{
			get
			{
				return this._ID_ESTDO;
			}
			set
			{
				if ((this._ID_ESTDO != value))
				{
					this._ID_ESTDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PAIS", DbType="SmallInt NOT NULL")]
		public short ID_PAIS
		{
			get
			{
				return this._ID_PAIS;
			}
			set
			{
				if ((this._ID_PAIS != value))
				{
					this._ID_PAIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLNIA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CLNIA
		{
			get
			{
				return this._CLNIA;
			}
			set
			{
				if ((this._CLNIA != value))
				{
					this._CLNIA = value;
				}
			}
		}
	}
	
	public partial class consultaMunicipioLocalidadResult
	{
		
		private short _ID_LCLDD;
		
		private short _ID_MNCPIO;
		
		private short _ID_ESTDO;
		
		private short _ID_PAIS;
		
		private string _LCLDD;
		
		public consultaMunicipioLocalidadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LCLDD", DbType="SmallInt NOT NULL")]
		public short ID_LCLDD
		{
			get
			{
				return this._ID_LCLDD;
			}
			set
			{
				if ((this._ID_LCLDD != value))
				{
					this._ID_LCLDD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MNCPIO", DbType="SmallInt NOT NULL")]
		public short ID_MNCPIO
		{
			get
			{
				return this._ID_MNCPIO;
			}
			set
			{
				if ((this._ID_MNCPIO != value))
				{
					this._ID_MNCPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTDO", DbType="SmallInt NOT NULL")]
		public short ID_ESTDO
		{
			get
			{
				return this._ID_ESTDO;
			}
			set
			{
				if ((this._ID_ESTDO != value))
				{
					this._ID_ESTDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PAIS", DbType="SmallInt NOT NULL")]
		public short ID_PAIS
		{
			get
			{
				return this._ID_PAIS;
			}
			set
			{
				if ((this._ID_PAIS != value))
				{
					this._ID_PAIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCLDD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LCLDD
		{
			get
			{
				return this._LCLDD;
			}
			set
			{
				if ((this._LCLDD != value))
				{
					this._LCLDD = value;
				}
			}
		}
	}
	
	public partial class consultaPaisEstadoResult
	{
		
		private short _ID_ESTDO;
		
		private short _ID_PAIS;
		
		private string _ESTDO;
		
		public consultaPaisEstadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTDO", DbType="SmallInt NOT NULL")]
		public short ID_ESTDO
		{
			get
			{
				return this._ID_ESTDO;
			}
			set
			{
				if ((this._ID_ESTDO != value))
				{
					this._ID_ESTDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PAIS", DbType="SmallInt NOT NULL")]
		public short ID_PAIS
		{
			get
			{
				return this._ID_PAIS;
			}
			set
			{
				if ((this._ID_PAIS != value))
				{
					this._ID_PAIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTDO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ESTDO
		{
			get
			{
				return this._ESTDO;
			}
			set
			{
				if ((this._ESTDO != value))
				{
					this._ESTDO = value;
				}
			}
		}
	}
	
	public partial class fechaServidorResult
	{
		
		private System.DateTime _FechaActual;
		
		public fechaServidorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActual", DbType="DateTime NOT NULL")]
		public System.DateTime FechaActual
		{
			get
			{
				return this._FechaActual;
			}
			set
			{
				if ((this._FechaActual != value))
				{
					this._FechaActual = value;
				}
			}
		}
	}
	
	public partial class llamarTurnoResult
	{
		
		private System.Nullable<int> _ID_TURNO;
		
		private System.Nullable<int> _NUMERO_TURNO;
		
		private System.Nullable<System.DateTime> _FECHA_ATENDIDO;
		
		private System.Nullable<short> _ID_UNIDAD_TURNO;
		
		private string _NOMBRE;
		
		private string _PATERNO;
		
		private string _MATERNO;
		
		public llamarTurnoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TURNO", DbType="Int")]
		public System.Nullable<int> ID_TURNO
		{
			get
			{
				return this._ID_TURNO;
			}
			set
			{
				if ((this._ID_TURNO != value))
				{
					this._ID_TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_TURNO", DbType="Int")]
		public System.Nullable<int> NUMERO_TURNO
		{
			get
			{
				return this._NUMERO_TURNO;
			}
			set
			{
				if ((this._NUMERO_TURNO != value))
				{
					this._NUMERO_TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ATENDIDO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_ATENDIDO
		{
			get
			{
				return this._FECHA_ATENDIDO;
			}
			set
			{
				if ((this._FECHA_ATENDIDO != value))
				{
					this._FECHA_ATENDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_UNIDAD_TURNO", DbType="SmallInt")]
		public System.Nullable<short> ID_UNIDAD_TURNO
		{
			get
			{
				return this._ID_UNIDAD_TURNO;
			}
			set
			{
				if ((this._ID_UNIDAD_TURNO != value))
				{
					this._ID_UNIDAD_TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PATERNO", DbType="VarChar(50)")]
		public string PATERNO
		{
			get
			{
				return this._PATERNO;
			}
			set
			{
				if ((this._PATERNO != value))
				{
					this._PATERNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATERNO", DbType="VarChar(50)")]
		public string MATERNO
		{
			get
			{
				return this._MATERNO;
			}
			set
			{
				if ((this._MATERNO != value))
				{
					this._MATERNO = value;
				}
			}
		}
	}
	
	public partial class TurnoMaxAtencionResult
	{
		
		private int _ID_TURNO;
		
		private int _TURNO;
		
		public TurnoMaxAtencionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TURNO", DbType="Int NOT NULL")]
		public int ID_TURNO
		{
			get
			{
				return this._ID_TURNO;
			}
			set
			{
				if ((this._ID_TURNO != value))
				{
					this._ID_TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TURNO", DbType="Int NOT NULL")]
		public int TURNO
		{
			get
			{
				return this._TURNO;
			}
			set
			{
				if ((this._TURNO != value))
				{
					this._TURNO = value;
				}
			}
		}
	}
	
	public partial class TurnoMaxMediacionResult
	{
		
		private int _ID_TURNO;
		
		private int _TURNO;
		
		public TurnoMaxMediacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TURNO", DbType="Int NOT NULL")]
		public int ID_TURNO
		{
			get
			{
				return this._ID_TURNO;
			}
			set
			{
				if ((this._ID_TURNO != value))
				{
					this._ID_TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TURNO", DbType="Int NOT NULL")]
		public int TURNO
		{
			get
			{
				return this._TURNO;
			}
			set
			{
				if ((this._TURNO != value))
				{
					this._TURNO = value;
				}
			}
		}
	}
	
	public partial class TurnoMaxOficialiaResult
	{
		
		private int _ID_TURNO;
		
		private int _TURNO;
		
		public TurnoMaxOficialiaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TURNO", DbType="Int NOT NULL")]
		public int ID_TURNO
		{
			get
			{
				return this._ID_TURNO;
			}
			set
			{
				if ((this._ID_TURNO != value))
				{
					this._ID_TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TURNO", DbType="Int NOT NULL")]
		public int TURNO
		{
			get
			{
				return this._TURNO;
			}
			set
			{
				if ((this._TURNO != value))
				{
					this._TURNO = value;
				}
			}
		}
	}
	
	public partial class TurnoMaxOrientacionResult
	{
		
		private int _ID_TURNO;
		
		private int _TURNO;
		
		public TurnoMaxOrientacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TURNO", DbType="Int NOT NULL")]
		public int ID_TURNO
		{
			get
			{
				return this._ID_TURNO;
			}
			set
			{
				if ((this._ID_TURNO != value))
				{
					this._ID_TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TURNO", DbType="Int NOT NULL")]
		public int TURNO
		{
			get
			{
				return this._TURNO;
			}
			set
			{
				if ((this._TURNO != value))
				{
					this._TURNO = value;
				}
			}
		}
	}
	
	public partial class consultaIdPersonaMaxResult
	{
		
		private System.Nullable<int> _ID_PERSONA;
		
		public consultaIdPersonaMaxResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERSONA", DbType="Int")]
		public System.Nullable<int> ID_PERSONA
		{
			get
			{
				return this._ID_PERSONA;
			}
			set
			{
				if ((this._ID_PERSONA != value))
				{
					this._ID_PERSONA = value;
				}
			}
		}
	}
	
	public partial class consultaMarcaSubMarcaResult
	{
		
		private short _id_marca;
		
		private short _id_submarca;
		
		private string _marca;
		
		private string _submarca;
		
		public consultaMarcaSubMarcaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_marca", DbType="SmallInt NOT NULL")]
		public short id_marca
		{
			get
			{
				return this._id_marca;
			}
			set
			{
				if ((this._id_marca != value))
				{
					this._id_marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_submarca", DbType="SmallInt NOT NULL")]
		public short id_submarca
		{
			get
			{
				return this._id_submarca;
			}
			set
			{
				if ((this._id_submarca != value))
				{
					this._id_submarca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(60)")]
		public string marca
		{
			get
			{
				return this._marca;
			}
			set
			{
				if ((this._marca != value))
				{
					this._marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_submarca", DbType="VarChar(60)")]
		public string submarca
		{
			get
			{
				return this._submarca;
			}
			set
			{
				if ((this._submarca != value))
				{
					this._submarca = value;
				}
			}
		}
	}
	
	public partial class SolicitarNucResult
	{
		
		private string _NUC;
		
		public SolicitarNucResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUC", DbType="VarChar(20)")]
		public string NUC
		{
			get
			{
				return this._NUC;
			}
			set
			{
				if ((this._NUC != value))
				{
					this._NUC = value;
				}
			}
		}
	}
	
	public partial class ConsultaImputadoDefensorResult
	{
		
		private string _IMPUTADO;
		
		private System.Nullable<int> _ID_PERSONA;
		
		public ConsultaImputadoDefensorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMPUTADO", DbType="VarChar(152)")]
		public string IMPUTADO
		{
			get
			{
				return this._IMPUTADO;
			}
			set
			{
				if ((this._IMPUTADO != value))
				{
					this._IMPUTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERSONA", DbType="Int")]
		public System.Nullable<int> ID_PERSONA
		{
			get
			{
				return this._ID_PERSONA;
			}
			set
			{
				if ((this._ID_PERSONA != value))
				{
					this._ID_PERSONA = value;
				}
			}
		}
	}
	
	public partial class consultaAccionDelitoResult
	{
		
		private short _ID_ACCION;
		
		private string _ACCION;
		
		public consultaAccionDelitoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ACCION", DbType="SmallInt NOT NULL")]
		public short ID_ACCION
		{
			get
			{
				return this._ID_ACCION;
			}
			set
			{
				if ((this._ID_ACCION != value))
				{
					this._ID_ACCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCION", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ACCION
		{
			get
			{
				return this._ACCION;
			}
			set
			{
				if ((this._ACCION != value))
				{
					this._ACCION = value;
				}
			}
		}
	}
	
	public partial class consultaPusoDisposicionResult
	{
		
		private System.Nullable<short> _ID_PUSO_DISPOSICION;
		
		private string _PUSO_DISPOSICION;
		
		public consultaPusoDisposicionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PUSO_DISPOSICION", DbType="SmallInt")]
		public System.Nullable<short> ID_PUSO_DISPOSICION
		{
			get
			{
				return this._ID_PUSO_DISPOSICION;
			}
			set
			{
				if ((this._ID_PUSO_DISPOSICION != value))
				{
					this._ID_PUSO_DISPOSICION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUSO_DISPOSICION", DbType="VarChar(50)")]
		public string PUSO_DISPOSICION
		{
			get
			{
				return this._PUSO_DISPOSICION;
			}
			set
			{
				if ((this._PUSO_DISPOSICION != value))
				{
					this._PUSO_DISPOSICION = value;
				}
			}
		}
	}
	
	public partial class MarcadorDenuncianteResult
	{
		
		private string _DENUNCIANTE;
		
		private System.Nullable<int> _ID_PERSONA;
		
		public MarcadorDenuncianteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENUNCIANTE", DbType="VarChar(152)")]
		public string DENUNCIANTE
		{
			get
			{
				return this._DENUNCIANTE;
			}
			set
			{
				if ((this._DENUNCIANTE != value))
				{
					this._DENUNCIANTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERSONA", DbType="Int")]
		public System.Nullable<int> ID_PERSONA
		{
			get
			{
				return this._ID_PERSONA;
			}
			set
			{
				if ((this._ID_PERSONA != value))
				{
					this._ID_PERSONA = value;
				}
			}
		}
	}
	
	public partial class MarcadorOfendidoResult
	{
		
		private string _OFENDIDO;
		
		private System.Nullable<int> _ID_PERSONA;
		
		public MarcadorOfendidoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFENDIDO", DbType="VarChar(152)")]
		public string OFENDIDO
		{
			get
			{
				return this._OFENDIDO;
			}
			set
			{
				if ((this._OFENDIDO != value))
				{
					this._OFENDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERSONA", DbType="Int")]
		public System.Nullable<int> ID_PERSONA
		{
			get
			{
				return this._ID_PERSONA;
			}
			set
			{
				if ((this._ID_PERSONA != value))
				{
					this._ID_PERSONA = value;
				}
			}
		}
	}
	
	public partial class MarcadorImputadoResult
	{
		
		private string _IMPUTADO;
		
		private System.Nullable<int> _ID_PERSONA;
		
		public MarcadorImputadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMPUTADO", DbType="VarChar(152)")]
		public string IMPUTADO
		{
			get
			{
				return this._IMPUTADO;
			}
			set
			{
				if ((this._IMPUTADO != value))
				{
					this._IMPUTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERSONA", DbType="Int")]
		public System.Nullable<int> ID_PERSONA
		{
			get
			{
				return this._ID_PERSONA;
			}
			set
			{
				if ((this._ID_PERSONA != value))
				{
					this._ID_PERSONA = value;
				}
			}
		}
	}
	
	public partial class MarcadorTestigoResult
	{
		
		private string _TESTIGO;
		
		private System.Nullable<int> _ID_PERSONA;
		
		public MarcadorTestigoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TESTIGO", DbType="VarChar(152)")]
		public string TESTIGO
		{
			get
			{
				return this._TESTIGO;
			}
			set
			{
				if ((this._TESTIGO != value))
				{
					this._TESTIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERSONA", DbType="Int")]
		public System.Nullable<int> ID_PERSONA
		{
			get
			{
				return this._ID_PERSONA;
			}
			set
			{
				if ((this._ID_PERSONA != value))
				{
					this._ID_PERSONA = value;
				}
			}
		}
	}
	
	public partial class MarcadorDefensorResult
	{
		
		private string _DEFENSOR;
		
		private int _ID_DEFENSOR;
		
		public MarcadorDefensorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEFENSOR", DbType="VarChar(152)")]
		public string DEFENSOR
		{
			get
			{
				return this._DEFENSOR;
			}
			set
			{
				if ((this._DEFENSOR != value))
				{
					this._DEFENSOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DEFENSOR", DbType="Int NOT NULL")]
		public int ID_DEFENSOR
		{
			get
			{
				return this._ID_DEFENSOR;
			}
			set
			{
				if ((this._ID_DEFENSOR != value))
				{
					this._ID_DEFENSOR = value;
				}
			}
		}
	}
	
	public partial class InvitadoNombreNUMResult
	{
		
		private string _INVITADO;
		
		private System.Nullable<int> _ID_PERSONA;
		
		public InvitadoNombreNUMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INVITADO", DbType="VarChar(152)")]
		public string INVITADO
		{
			get
			{
				return this._INVITADO;
			}
			set
			{
				if ((this._INVITADO != value))
				{
					this._INVITADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERSONA", DbType="Int")]
		public System.Nullable<int> ID_PERSONA
		{
			get
			{
				return this._ID_PERSONA;
			}
			set
			{
				if ((this._ID_PERSONA != value))
				{
					this._ID_PERSONA = value;
				}
			}
		}
	}
	
	public partial class SolicitanteNombreNUMResult
	{
		
		private string _SOLICITANTE;
		
		private System.Nullable<int> _ID_PERSONA;
		
		public SolicitanteNombreNUMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLICITANTE", DbType="VarChar(152)")]
		public string SOLICITANTE
		{
			get
			{
				return this._SOLICITANTE;
			}
			set
			{
				if ((this._SOLICITANTE != value))
				{
					this._SOLICITANTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERSONA", DbType="Int")]
		public System.Nullable<int> ID_PERSONA
		{
			get
			{
				return this._ID_PERSONA;
			}
			set
			{
				if ((this._ID_PERSONA != value))
				{
					this._ID_PERSONA = value;
				}
			}
		}
	}
	
	public partial class consultaIdAcuerdoDiferidoMaxResult
	{
		
		private System.Nullable<int> _ID_NUM_CUM_DIFERIDO;
		
		public consultaIdAcuerdoDiferidoMaxResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NUM_CUM_DIFERIDO", DbType="Int")]
		public System.Nullable<int> ID_NUM_CUM_DIFERIDO
		{
			get
			{
				return this._ID_NUM_CUM_DIFERIDO;
			}
			set
			{
				if ((this._ID_NUM_CUM_DIFERIDO != value))
				{
					this._ID_NUM_CUM_DIFERIDO = value;
				}
			}
		}
	}
	
	public partial class SP_ComboFotoResult
	{
		
		private int _IdFotografia;
		
		private string _Descripcion;
		
		public SP_ComboFotoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFotografia", DbType="Int NOT NULL")]
		public int IdFotografia
		{
			get
			{
				return this._IdFotografia;
			}
			set
			{
				if ((this._IdFotografia != value))
				{
					this._IdFotografia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
